# Welcome to my notebook
get help on a virtual environment

python -m venv -h

# create a virtual environment .venv
python -m venv .venv

# activate the virtual environement 

source .venv/bin/activate

# most needed lib needed for ML
 pandas - matplotlib - numpy - scikit-learn - ipykernel

pip install pandas matplotlib numpy scikit-learn ipykernel 

In [2]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0])
print(a[1])
print(a[2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [3]:
import matplotlib.pyplot as plt
import numpy as np 
from sklearn import datasets, linear_model, model_selection

# Load the diabetes dataset 

X, y = datasets.load_diabetes(return_X_y=True)

# Print the shape of the data and the first row

print(X.shape)
print(X[0])

(442, 10)
[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
 -0.04340085 -0.00259226  0.01990749 -0.01764613]


In [4]:
# Extract the column at index 2
X = X[:, 2]
print(X.shape)

# Reshape to a 20 array 
X = X.reshape((-1, 1))
print(X.shape)


(442,)
(442, 1)


In [1]:
print(" hello Notebook")

 hello Notebook
