# Welcome to my notebook
get help on a virtual environment

python -m venv -h

# create a virtual environment .venv
python -m venv .venv

# activate the virtual environement 

source .venv/bin/activate

# most needed lib needed for ML
 pandas - matplotlib - numpy - scikit-learn - ipykernel

pip install pandas matplotlib numpy scikit-learn ipykernel 

In [2]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0])
print(a[1])
print(a[2])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [1]:
print(" hello Notebook")

 hello Notebook
